name: mailapp
description: "Flutter desktop app for sending emails."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  macos_ui: ^2.0.5
  path_provider: ^2.1.2
  path: ^1.9.0
  # state management
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  provider: ^6.1.1
  rxdart: ^0.27.7
  # storage
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.20
  sqlite3: ^2.4.0
  uuid: ^3.0.7
  # editor
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor
      path: super_editor
      ref: stable
  url_launcher: ^6.2.4
  google_generative_ai: ^0.2.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  drift_dev: ^2.15.0
  build_runner: ^2.4.8

dependency_overrides:
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor
      path: super_editor
      ref: stable # or "main"
  super_editor_markdown:
    git:
      url: https://github.com/superlistapp/super_editor
      path: super_editor_markdown
      ref: stable
  super_text_layout:
    git:
      url: https://github.com/superlistapp/super_editor
      path: super_text_layout
      ref: stable
  attributed_text:
    git:
      url: https://github.com/superlistapp/super_editor
      path: attributed_text
      ref: stable

flutter:
  uses-material-design: true
